# Implimenting CNN from scratch

In [7]:
import numpy as np


def convolve2d(image, kernel, stride=1, padding=0):
    kernel = np.flipud(np.fliplr(kernel))  # Flip the kernel
    x_img, y_img = image.shape
    x_kern, y_kern = kernel.shape
    
    x_out = int((x_img - x_kern + 2 * padding) / stride) + 1
    y_out = int((y_img - y_kern + 2 * padding) / stride) + 1

    # Padding
    if padding != 0:
        image_padded = np.zeros((x_img + padding*2, y_img + padding*2))
        image_padded[padding:-padding, padding:-padding] = image
    else:
        image_padded = image

    output = np.zeros((x_out, y_out))

    for y in range(0, y_out):
        for x in range(0, x_out):
            output[x, y] = np.sum(kernel * image_padded[x*stride:x*stride+x_kern, y*stride:y*stride+y_kern])

    return output

def relu(feature_map):
    return np.maximum(0, feature_map)

def max_pooling(feature_map, size=2, stride=2):
    x, y = feature_map.shape
    x_pool = int((x - size) / stride) + 1
    y_pool = int((y - size) / stride) + 1

    output = np.zeros((x_pool, y_pool))
    
    for i in range(0, x_pool):
        for j in range(0, y_pool):
            output[i, j] = np.max(feature_map[i*stride:i*stride+size, j*stride:j*stride+size])
    return output

def flatten(feature_map):
    return feature_map.flatten()

def dense(flattened, weights=None, bias=None, output_units=2):
    if weights is None:
        np.random.seed(0)
        weights = np.random.randn(output_units, flattened.shape[0])
    if bias is None:
        bias = np.random.randn(output_units)
    return np.dot(weights, flattened) + bias



image = np.array([
    [3, 0, 1, 2, 7],
    [1, 5, 8, 9, 3],
    [2, 7, 2, 5, 1],
    [0, 1, 3, 1, 7],
    [4, 2, 1, 6, 2]
])


kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])


np.random.seed(0)
dense_weights = np.random.randn(2, 4)  # 2 outputs, 4 inputs (depends on flatten size)
dense_bias = np.random.randn(2)



# implimentation of cnn 

# Step 1: Convolution
conv_out = convolve2d(image, kernel, stride=1, padding=0)
print("Convolution Output:\n", conv_out)

# Step 2: ReLU Activation
relu_out = relu(conv_out)
print("\nReLU Output:\n", relu_out)

# Step 3: Max Pooling
pool_out = max_pooling(relu_out, size=2, stride=2)
print("\nMax Pooling Output:\n", pool_out)

# Step 4: Flatten
flat_out = flatten(pool_out)
print("\nFlatten Output:\n", flat_out)

# Step 5: Dense Layer
dense_out = dense(flat_out)
print("\nDense Output (Final Predictions):\n", dense_out)



Convolution Output:
 [[ 5.  4.  0.]
 [10.  2. -2.]
 [ 0.  2.  4.]]

ReLU Output:
 [[ 5.  4.  0.]
 [10.  2.  0.]
 [ 0.  2.  4.]]

Max Pooling Output:
 [[10.]]

Flatten Output:
 [10.]

Dense Output (Final Predictions):
 [18.61926144  6.24246528]
